export const categories = [
  { id: "cleaning", label: "Cleaning", icon: "Sparkles" },
  { id: "plumbing", label: "Plumbing", icon: "Wrench" },
  { id: "electrical", label: "Electrical", icon: "PlugZap" },
  { id: "cooking", label: "Cooking", icon: "CookingPot" },
  { id: "repairs", label: "Home Repairs", icon: "Hammer" },
  { id: "gardening", label: "Gardening", icon: "Leaf" },
  { id: "painting", label: "Painting", icon: "Brush" },
  { id: "tutoring", label: "Tutoring", icon: "BookOpen" },
];

export const services = [
  {
    id: 1,
    name: "Full Home Cleaning",
    category: "cleaning",
    categoryLabel: "Cleaning",
    price: 2499,
    rating: 4.8,
    reviews: 342,
    duration: "4 hours",
    booked: 1290,
    verified: true,
    popular: true,
    description:
      "Deep cleaning of the entire home including bathrooms, kitchen, floors and appliances using eco-friendly products.",
    inclusions: [
      "All rooms, kitchen and bathrooms",
      "Eco-friendly cleaning products",
      "Trained field staff",
      "Satisfaction guarantee",
    ],
    providerIds: [1, 3],
  },
  {
    id: 2,
    name: "Plumbing Repair",
    category: "plumbing",
    categoryLabel: "Plumbing",
    price: 399,
    rating: 4.7,
    reviews: 218,
    duration: "2 hours",
    booked: 870,
    verified: true,
    popular: true,
    description:
      "Fix leakages, blocked drains, faulty taps, geysers and WC fittings with guaranteed workmanship.",
    inclusions: [
      "Final pricing before work starts",
      "Genuine spares only",
      "30-day work warranty",
    ],
    providerIds: [2],
  },
  {
    id: 3,
    name: "AC Servicing & Repair",
    category: "electrical",
    categoryLabel: "Electrical",
    price: 549,
    rating: 4.6,
    reviews: 156,
    duration: "1.5 hours",
    booked: 640,
    verified: true,
    popular: true,
    description:
      "AC gas top-up, deep cleaning, general servicing and repair for all major brands of split and window ACs.",
    inclusions: [
      "All major brands covered",
      "Gas leak detection",
      "90-day spare warranty",
    ],
    providerIds: [4],
  },
  {
    id: 4,
    name: "Home Cook (Daily Tiffin)",
    category: "cooking",
    categoryLabel: "Cooking",
    price: 4500,
    rating: 4.9,
    reviews: 189,
    duration: "per month",
    booked: 420,
    verified: true,
    popular: true,
    description:
      "Hygienic home-style lunch and dinner cooked by verified local cooks with authentic regional taste.",
    inclusions: [
      "Monthly tiffin service",
      "Customisable menu",
      "Hygiene-certified cooks",
      "Free delivery in 2 km radius",
    ],
    providerIds: [5, 6],
  },
  {
    id: 5,
    name: "Furniture & Carpenter Work",
    category: "repairs",
    categoryLabel: "Home Repairs",
    price: 499,
    rating: 4.5,
    reviews: 98,
    duration: "3 hours",
    booked: 310,
    verified: false,
    popular: false,
    description:
      "Carpentry for broken furniture, doors, windows, wardrobes, locks and modular kitchen repairs.",
    inclusions: [
      "All wood & laminates work",
      "On-site estimates",
      "Polished finish",
    ],
    providerIds: [2],
  },
  {
    id: 6,
    name: "Garden & Terrace Maintenance",
    category: "gardening",
    categoryLabel: "Gardening",
    price: 899,
    rating: 4.7,
    reviews: 121,
    duration: "3 hours",
    booked: 265,
    verified: true,
    popular: false,
    description:
      "Lawn mowing, pruning, potting, pest control and complete garden / terrace upkeep on a monthly plan.",
    inclusions: [
      "Monthly maintenance plan",
      "Organic pest control",
      "Plant health checkups",
    ],
    providerIds: [3],
  },
  {
    id: 7,
    name: "Painting (Single Room)",
    category: "painting",
    categoryLabel: "Painting",
    price: 3499,
    rating: 4.4,
    reviews: 77,
    duration: "6 hours",
    booked: 190,
    verified: true,
    popular: false,
    description:
      "Interior wall painting for single rooms with premium Asian Paints/Berger finish and clean-up included.",
    inclusions: [
      "Premium brand paints",
      "Surface preparation",
      "Same-day completion",
      "Post-work cleanup",
    ],
    providerIds: [3, 4],
  },
  {
    id: 8,
    name: "Maths Tutoring (Classes 6-10)",
    category: "tutoring",
    categoryLabel: "Tutoring",
    price: 2000,
    rating: 4.8,
    reviews: 143,
    duration: "per month",
    booked: 350,
    verified: true,
    popular: false,
    description:
      "Personalised maths tuition at home with weekly tests, doubt-clearing sessions and parent progress reports.",
    inclusions: [
      "Home or online sessions",
      "Weekly practice tests",
      "Monthly progress report",
    ],
    providerIds: [6],
  },
];

export const providers = [
  {
    id: 1,
    name: "Rekha Kumari",
    role: "Professional Cleaner",
    category: "cleaning",
    rating: 4.9,
    reviews: 210,
    jobs: 1450,
    verified: true,
    cooperative: "Nari Shakti Cooperative",
    location: "Koramangala, Bengaluru",
    experience: "6 years",
    skills: ["Home Cleaning", "Deep Cleaning", "Office Cleaning"],
    languages: ["Hindi", "Kannada"],
    price: 2499,
    about:
      "Rekha leads a team of 12 trained women cleaners from her neighbourhood cooperative. She has completed 1400+ jobs with a 98% satisfaction score.",
    avatar: "RK",
    color: "violet",
    available: true,
    memberSince: "2023",
  },
  {
    id: 2,
    name: "Mohammed Irfan",
    role: "Plumber & Carpenter",
    category: "plumbing",
    rating: 4.7,
    reviews: 168,
    jobs: 980,
    verified: true,
    cooperative: "Saathi Workers Collective",
    location: "Indiranagar, Bengaluru",
    experience: "9 years",
    skills: ["Plumbing", "Pipe Fitting", "Carpentry", "Tiling"],
    languages: ["Hindi", "Urdu", "Kannada"],
    price: 399,
    about:
      "Irfan is a government-certified plumber and a founding member of the Saathi Workers Collective, known for fair pricing and honest estimates.",
    avatar: "MI",
    color: "blue",
    available: true,
    memberSince: "2022",
  },
  {
    id: 3,
    name: "Sunita Devi",
    role: "Gardener & Handywoman",
    category: "gardening",
    rating: 4.8,
    reviews: 134,
    jobs: 760,
    verified: true,
    cooperative: "Green Valley Cooperatives",
    location: "Whitefield, Bengaluru",
    experience: "5 years",
    skills: ["Gardening", "Landscaping", "Home Repairs"],
    languages: ["Hindi", "Telugu"],
    price: 899,
    about:
      "Sunita maintains more than 80 home gardens and terraces. Her cooperative trains women in organic gardening and urban farming.",
    avatar: "SD",
    color: "green",
    available: true,
    memberSince: "2023",
  },
  {
    id: 4,
    name: "Vijay Salian",
    role: "AC & Electrical Technician",
    category: "electrical",
    rating: 4.6,
    reviews: 92,
    jobs: 540,
    verified: true,
    cooperative: "Urban Skill Co-op",
    location: "HSR Layout, Bengaluru",
    experience: "8 years",
    skills: ["AC Repair", "Wiring", "Appliances", "Inverters"],
    languages: ["Hindi", "Kannada", "English"],
    price: 549,
    about:
      "Vijay is an ITI-certified technician specialising in AC and appliance repair. He trains apprentices from his cooperative every quarter.",
    avatar: "VS",
    color: "orange",
    available: false,
    memberSince: "2022",
  },
  {
    id: 5,
    name: "Pushpa Rani",
    role: "Home Cook (Tiffin)",
    category: "cooking",
    rating: 4.9,
    reviews: 176,
    jobs: 890,
    verified: true,
    cooperative: "Annapurna Cooks Co-op",
    location: "JP Nagar, Bengaluru",
    experience: "7 years",
    skills: ["South Indian", "North Indian", "Bulk Cooking", "Tiffin Service"],
    languages: ["Kannada", "Tamil", "Hindi"],
    price: 4500,
    about:
      "Pushpa runs a famous weekly tiffin service through the Annapurna Cooks Cooperative, delivering 200+ meals daily with FSSAI hygiene licence.",
    avatar: "PR",
    color: "pink",
    available: true,
    memberSince: "2021",
  },
  {
    id: 6,
    name: "Arjun Mehta",
    role: "Tutor & Home Cook",
    category: "tutoring",
    rating: 4.8,
    reviews: 118,
    jobs: 620,
    verified: true,
    cooperative: "Learn Local Co-op",
    location: "Malleshwaram, Bengaluru",
    experience: "4 years",
    skills: ["Maths", "Science", "English", "Meal Prep"],
    languages: ["Hindi", "Kannada", "English"],
    price: 2000,
    about:
      "Arjun is a graduate tutor who also offers healthy tiffin meal prep. He is a mentor for 20+ student-volunteers in his cooperative.",
    avatar: "AM",
    color: "cyan",
    available: true,
    memberSince: "2024",
  },
];

export const bookings = [
  {
    id: "BK-7841",
    customer: "Ananya Sharma",
    customerId: "CU-1021",
    providerId: 1,
    serviceId: 1,
    date: "2026-09-18",
    time: "10:00 AM",
    price: 2499,
    status: "confirmed",
    address: "405, 4th Cross, Koramangala, Bengaluru",
    notes: "Please focus on the kitchen and balcony windows.",
    payment: "UPI",
    rating: null,
  },
  {
    id: "BK-7840",
    customer: "Rahul Verma",
    customerId: "CU-1004",
    providerId: 2,
    serviceId: 2,
    date: "2026-09-16",
    time: "02:00 PM",
    price: 399,
    status: "pending",
    address: "102, 12th Main, Indiranagar, Bengaluru",
    notes: "Kitchen sink pipe leaking since morning.",
    payment: "Cash",
    rating: null,
  },
  {
    id: "BK-7836",
    customer: "Priya Nair",
    customerId: "CU-1011",
    providerId: 6,
    serviceId: 8,
    date: "2026-09-12",
    time: "05:30 PM",
    price: 2000,
    status: "completed",
    address: "23, 3rd Block, Malleshwaram, Bengaluru",
    notes: "Need help with Class 9 algebra.",
    payment: "UPI",
    rating: 5,
  },
  {
    id: "BK-7832",
    customer: "Ananya Sharma",
    customerId: "CU-1021",
    providerId: 3,
    serviceId: 6,
    date: "2026-09-10",
    time: "08:00 AM",
    price: 899,
    status: "completed",
    address: "405, 4th Cross, Koramangala, Bengaluru",
    notes: "",
    payment: "UPI",
    rating: 5,
  },
  {
    id: "BK-7829",
    customer: "Suresh Reddy",
    customerId: "CU-1017",
    providerId: 4,
    serviceId: 3,
    date: "2026-09-08",
    time: "11:00 AM",
    price: 549,
    status: "cancelled",
    address: "88, 5th Main, HSR Layout, Bengaluru",
    notes: "AC not cooling.",
    payment: "UPI",
    rating: null,
  },
  {
    id: "BK-7826",
    customer: "Meera Iyer",
    customerId: "CU-1009",
    providerId: 5,
    serviceId: 4,
    date: "2026-09-06",
    time: "12:30 PM",
    price: 4500,
    status: "completed",
    address: "15, 2nd Stage, JP Nagar, Bengaluru",
    notes: "Monthly tiffin plan, veg only.",
    payment: "Card",
    rating: 4,
  },
  {
    id: "BK-7821",
    customer: "Ananya Sharma",
    customerId: "CU-1021",
    providerId: 2,
    serviceId: 5,
    date: "2026-09-04",
    time: "09:00 AM",
    price: 499,
    status: "cancelled",
    address: "405, 4th Cross, Koramangala, Bengaluru",
    notes: "",
    payment: "Cash",
    rating: null,
  },
];

export const users = [
  { id: "CU-1021", name: "Ananya Sharma", type: "customer", email: "ananya@example.com", joined: "2025-11-12", bookings: 24, phone: "+91 98xxxxx210", location: "Koramangala, Bengaluru" },
  { id: "SP-221", name: "Rekha Kumari", type: "provider", email: "rekha@example.com", joined: "2023-02-01", bookings: 1450, phone: "+91 98xxxxx745", location: "Koramangala, Bengaluru" },
  { id: "SP-318", name: "Mohammed Irfan", type: "provider", email: "irfan@example.com", joined: "2022-06-14", bookings: 980, phone: "+91 97xxxxx331", location: "Indiranagar, Bengaluru" },
  { id: "CU-1004", name: "Rahul Verma", type: "customer", email: "rahul@example.com", joined: "2026-01-08", bookings: 9, phone: "+91 95xxxxx882", location: "Indiranagar, Bengaluru" },
  { id: "CU-1011", name: "Priya Nair", type: "customer", email: "priya@example.com", joined: "2025-09-21", bookings: 31, phone: "+91 99xxxxx224", location: "Malleshwaram, Bengaluru" },
  { id: "AD-001", name: "Sahayog Admin", type: "admin", email: "admin@sahayog.in", joined: "2022-01-01", bookings: 0, phone: "+91 80xxxxx000", location: "Bengaluru" },
];

export const communityGroups = [
  {
    id: 1,
    name: "Nari Shakti Cooperative",
    members: 140,
    type: "Women's Collective",
    city: "Koramangala",
    about: "Empowering women through professional cleaning and housekeeping services.",
    membersList: ["Rekha Kumari", "Meena W.", "Lakshmi B."],
    verified: true,
  },
  {
    id: 2,
    name: "Saathi Workers Collective",
    members: 85,
    type: "Skilled Workers",
    city: "Indiranagar",
    about: "Certified plumbers, carpenters and electricians with fair pricing.",
    membersList: ["Mohammed Irfan", "Suresh P.", "Ganesh K."],
    verified: true,
  },
  {
    id: 3,
    name: "Annapurna Cooks Co-op",
    members: 120,
    type: "Food & Hospitality",
    city: "JP Nagar",
    about: "FSSAI-certified home cooks delivering healthy meals across the city.",
    membersList: ["Pushpa Rani", "Kavya S.", "Devika R."],
    verified: true,
  },
  {
    id: 4,
    name: "Green Valley Farmers",
    members: 65,
    type: "Farming & Gardening",
    city: "Whitefield",
    about: "Urban gardeners and terrace-farmers growing fresh, organic produce.",
    membersList: ["Sunita Devi", "Ramesh G.", "Farah K."],
    verified: true,
  },
  {
    id: 5,
    name: "Learn Local Co-op",
    members: 50,
    type: "Education",
    city: "Malleshwaram",
    about: "Graduate tutors and volunteers making quality education affordable.",
    membersList: ["Arjun Mehta", "Nisha T.", "Pooja V."],
    verified: false,
  },
];

export const communityRequests = [
  {
    id: 1,
    group: "Nari Shakti Cooperative",
    title: "Need 5 cleaners for a society deep-clean contract",
    posted: "2 days ago",
    budget: "₹18,000",
    requester: "Green Meadows Society",
    status: "open",
  },
  {
    id: 2,
    group: "Saathi Workers Collective",
    title: "Urgent plumbing work for 30 flats renovation",
    posted: "5 days ago",
    budget: "₹42,000",
    requester: "Prestige Residency",
    status: "open",
  },
  {
    id: 3,
    group: "Annapurna Cooks Co-op",
    title: "Daily catering for a daycare (40 kids)",
    posted: "1 week ago",
    budget: "₹25,000/month",
    requester: "Little Sprouts Daycare",
    status: "filled",
  },
];

export const providerRequests = [
  {
    id: "REQ-501",
    customer: "Rahul Verma",
    service: "Plumbing Repair",
    date: "2026-09-16",
    time: "02:00 PM",
    price: 399,
    status: "pending",
    location: "Indiranagar, Bengaluru",
  },
  {
    id: "REQ-502",
    customer: "Sneha Kulkarni",
    service: "Full Home Cleaning",
    date: "2026-09-20",
    time: "09:00 AM",
    price: 2499,
    status: "pending",
    location: "HSR Layout, Bengaluru",
  },
  {
    id: "REQ-503",
    customer: "Farhan Ali",
    service: "AC Servicing & Repair",
    date: "2026-09-21",
    time: "04:00 PM",
    price: 549,
    status: "pending",
    location: "Whitefield, Bengaluru",
  },
];

export const providerEarnings = {
  total: "₹86,450",
  thisMonth: "₹21,300",
  rating: 4.8,
  completedJobs: 1450,
  activeJobs: 6,
  trend: "+12% vs last month",
  recent: [
    { label: "Week of 7 Sep", amount: "₹5,900", color: "blue" },
    { label: "Week of 31 Aug", amount: "₹6,400", color: "green" },
    { label: "Week of 24 Aug", amount: "₹4,800", color: "violet" },
    { label: "Week of 17 Aug", amount: "₹4,200", color: "orange" },
  ],
  reviews: [
    { from: "Ananya S.", text: "Impeccable cleaning. Booking again next month!", rating: 5 },
    { from: "Rakesh M.", text: "Arrived on time and did a thorough job.", rating: 5 },
    { from: "Divya G.", text: "Great work but slightly late.", rating: 4 },
  ],
};

export const adminStats = {
  totalUsers: 1480,
  totalProviders: 126,
  totalBookings: 5210,
  totalServices: 48,
  revenue: "₹32.4L",
  avgRating: 4.7,
  growth: "+18%",
};

export const reviews = [
  { id: 1, name: "Ananya S.", service: "Full Home Cleaning", provider: "Rekha Kumari", rating: 5, text: "Deep cleaning was spotless. The team was professional and polite.", date: "12 Sep 2026" },
  { id: 2, name: "Rahul V.", service: "Plumbing Repair", provider: "Mohammed Irfan", rating: 5, text: "Fixed the leak in 20 minutes. Fair price, no middleman.", date: "10 Sep 2026" },
  { id: 3, name: "Priya N.", service: "Maths Tutoring", provider: "Arjun Mehta", rating: 5, text: "My daughter's maths improved a lot. Very patient tutor.", date: "08 Sep 2026" },
  { id: 4, name: "Meera I.", service: "Home Cook (Daily Tiffin)", provider: "Pushpa Rani", rating: 4, text: "Tasty tiffin, consistent quality. A little more variety would be nice.", date: "06 Sep 2026" },
  { id: 5, name: "Suresh R.", service: "AC Servicing", provider: "Vijay Salian", rating: 5, text: "Diagnosed the issue instantly and charged exactly as quoted.", date: "05 Sep 2026" },
  { id: 6, name: "Kavya S.", service: "Garden Maintenance", provider: "Sunita Devi", rating: 5, text: "My terrace garden looks beautiful now. Very reasonable monthly plan.", date: "02 Sep 2026" },
];

export const formatINR = (n) => `₹${Number(n).toLocaleString("en-IN")}`;

export const getService = (id) => services.find((s) => s.id === Number(id));
export const getProvider = (id) => providers.find((p) => p.id === Number(id));
export const getBooking = (id) => bookings.find((b) => b.id === id);